package com.josimarsilva.projecteuler.java;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with and, the first terms will be:
 *    1,2,3,5,6,13,21,34,55,89,...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Ref.: <a href="https://projecteuler.net/problem=2">EvenFibonacciNumbers</a>
 */
public class EvenFibonacciNumbers {

    static EvenFibonacciNumbers find() {
        return new EvenFibonacciNumbers();
    }

    long sumUpTo(long limit) {
        var sum = 0;
        var previous = 1;
        var current = 2;

        while(current < limit) {
            if(current % 2 == 0) {
                sum += current;
            }
            final var next = previous + current;
            previous = current;
            current = next;
        }

        return sum;
    }
}
